name: play-sklearn
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pip=20.2.4
  - python=3.8
  - pip:
    - streamlit==1.8.1
    - scikit-learn==1.0.2
    - plotly==5.7.0
    - pandas==1.4.2
